// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Message struct {
	Id               *int32          `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Author           *Message_Person `protobuf:"bytes,2,req,name=author" json:"author,omitempty"`
	Text             *string         `protobuf:"bytes,3,req,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message) GetAuthor() *Message_Person {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type Message_Person struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Person) Reset()         { *m = Message_Person{} }
func (m *Message_Person) String() string { return proto.CompactTextString(m) }
func (*Message_Person) ProtoMessage()    {}

func (m *Message_Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message_Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}
